#!/bin/bash

EMP_WAGE_PER_HOUR=20
PRESENT=1
PART_TIME=2
WORKING_HOUR=8
MAX_WORKING_DAYS=20
MAX_WORKING_HOURS=40
TOTALWORKINGHOUR=0
day=0

while [[ $day -lt $MAX_WORKING_DAYS && $TOTALWORKINGHOUR -lt $MAX_WORKING_HOUR ]]
do
	if [ $TOTALWORKINGHOUR -eq $((MAX_WORKING_HOURS - WORKING_HOUR/2)) ]
   then 
		isPresent= PART_TIME
	else
		isPresent=$((RANDOM%3))
	fi
   $isPresent in
	$PRESENT)
		EMP_HOUR=$WORKING_HOUR
   ;;
   $PART_TIME)
		EMP_HOUR=$(WORKING_HOUR/2)
	;;
	*)
		dailywage=0
	;;
esac


